branch-defaults:
  main:
    environment: pdf-to-podcast-env
global:
  application_name: pdf-to-podcast
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: eu-west-2
  profile: null
  sc: git
